### ISSUE TITLE
The development scrips are broken

### ISSUE THREAD

**Issue by henkkuli** [AleksTeresh/master-thesis#5]
I tried to run the LCL classifier locally to debug #4. I have tried to follow the readme and ran
```
> npm install
> npm run dev
```
inside the `src/client` directory. The latter command gives me the following output:
```

> svelte-app@1.0.0 dev
> npm-run-all --parallel svelte-check-watch serve


> svelte-app@1.0.0 svelte-check-watch
> svelte-check --watch


> svelte-app@1.0.0 serve
> webpack serve --content-base public

[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/lib/webpack-cli.js:108:21)
    at ServeCommand.apply (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/node_modules/@webpack-cli/serve/lib/index.js:41:19)
    at loadCommandByName (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/lib/webpack-cli.js:626:35)
    at Command.<anonymous> (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/lib/webpack-cli.js:1091:23)
    at Command.listener [as _actionHandler] (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/node_modules/commander/index.js:1503:14)
    at Command.parse (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/node_modules/commander/index.js:1292:10)
    at Command.parseAsync (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/node_modules/commander/index.js:1318:10)
    at WebpackCLI.run (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/lib/webpack-cli.js:1123:28)
    at runCLI (/home/user/lcl-classifier/src/client/node_modules/webpack-cli/lib/bootstrap.js:11:19)
ERROR: "serve" exited with 2.
```

**Comment by jendas1** [comment]
@henkkuli probably related to an old version of "webpack-cli" (see https://github.com/dfinity/sdk/issues/1870 ). Can you try running it with modification of the `package.json` to have `"webpack-cli": "4.9.2"`?
